# .github/workflows/ci.yml
name: CI Ecommerce
permissions:
  contents: write
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-and-publish:
    runs-on:
      ubuntu-latest

      # INÍCIO DA CORREÇÃO: Inicia um serviço de banco de dados MySQL
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce_cart_db # O nome do DB que seus testes esperam
          MYSQL_USER: userdb
          MYSQL_PASSWORD: senhadb
        ports:
          - 3306:3306
        # Garante que os testes só comecem depois que o DB estiver pronto
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    # FIM DA CORREÇÃO
    # Define o diretório de trabalho padrão para todos os passos deste job
    defaults:
      run:
        working-directory: ./ecommerce-api

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: |
          cd ecommerce-api
          npm install

      - name: Instalar Allure Commandline
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          sudo tar -zxvf allure-2.27.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure
          allure --version

      - name: Executar testes (gerar Allure results)
        run: |
          cd ecommerce-api
          npm test
        # Continuar mesmo que os testes falhem, para que possamos publicar os resultados
        continue-on-error: true

      - name: Gerar Relatório Allure
        # Roda o comando para gerar o site estático na pasta allure-report
        run: |
          cd ecommerce-api
          allure generate allure-results --clean -o allure-report

      - name: Publicar resultados dos testes
        # Executa apenas em push para main, para não poluir o DB com execuções de PRs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cd ecommerce-api
          git add allure-report allure-results
          # Verifica se há algo para comitar antes de tentar
          git diff --staged --quiet || git commit -m "CI: Atualiza relatório de testes Allure"
          git push
          node scripts/publish-test-results.js

        env:
          # Configure estes segredos nas configurações do seu repositório no GitHub
          # Ex: https://your-domain.com/api/internal/test-results
          TEST_RESULTS_API_URL: ${{ secrets.TEST_RESULTS_API_URL }}
          INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
